[rtpengine]
table = 0
interface = public/10.10.0.133!54.220.131.205;tunnel/10.7.0.1
listen-ng = 127.0.0.1:2223
port-min = 30000
port-max = 40000
log-level = 6
delete-delay = 30
timeout = 60
silent-timeout = 3600
tos = 184
no-fallback = false
